### ISSUE TITLE
Rate in history

### ISSUE THREAD

**Issue by hairmenu** [florianv/laravel-swap#13]
Some providers allows to make history query so it would be nice to be able to perform something like
quote('EUR/USD', '2011-08-08').
Actually it is a deal killer for me. I wish i could use your package.

My 2 cents

**Comment by florianv** [comment]
Thanks for your suggestion. I'm linking it to the main Swap repo

**Comment by florianv** [comment]
@hairmenu This feature will be implemented in the new 3.0 Swap version. https://github.com/florianv/swap/pull/66
