### ISSUE TITLE
Installation through composer fails 

### ISSUE THREAD

**Issue by Suganya-Rajasekar** [florianv/laravel-swap#14]
Hi ,
When I run ''composer require florianv/laravel-swap" this command in teminal 

Using version ^0.4.0 for florianv/laravel-swap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
### Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzle/guzzle v3.9.3 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.9.3 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.9.3 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - Installation request for guzzle/guzzle == 3.9.3.0 -> satisfiable by guzzle/guzzle[v3.9.3].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by florianv** [comment]
The error message states that `the requested PHP extension curl is missing from your system.`.
So you need to install CURL.

**Comment by Suganya-Rajasekar** [comment]
I did it 
**curl -sS https://getcomposer.org/installer | php**
**sudo mv composer.phar /usr/local/bin/composer**
by using this commands..But it show me the same error..
