### ISSUE TITLE
Fetch all conversions at once

### ISSUE THREAD

**Issue by simplenotezy** [florianv/laravel-swap#2]
I miss a way to fetch all conversions at once. Say I have many different currencies I need to convert at the same page, I'll be making many requests at once.

**Comment by florianv** [comment]
Not all providers support retrieving multiple values at once, so you need to call the quote() method multiple times.

**Comment by simplenotezy** [comment]
OK. Would be great with such a feature for providers that support it

**Comment by florianv** [comment]
Yes, thanks for the suggestion :)

**Comment by florianv** [comment]
Closing this issue in favor of https://github.com/florianv/swap/issues/20
