### ISSUE TITLE
Support for laravel 5.3

### ISSUE THREAD

**Issue by ymantelli** [florianv/laravel-swap#23]
When you update composer the following errors occur : 
![capture](https://cloud.githubusercontent.com/assets/20010793/20758188/57873d62-b719-11e6-92a0-1e0054a0e8e4.PNG)

**Comment by florianv** [comment]
Hey,

this is because you need to install a `php-http/client-implementation` before Swap as stated on the documentation https://github.com/florianv/laravel-swap/blob/master/doc/readme.md#installation
