### ISSUE TITLE
FEATURE: Integration with Lumen

### ISSUE THREAD

**Issue by vongrad** [florianv/laravel-swap#24]
First of, thank you for a great library!

Since many developers including me are using Lumen, I wanted to ask you, whether you could implement an integration between those two. It would really come in handy. I managed to integrate your library with Lumen, however I could not do so without modifying your code - which is bad in a sense that I cannot keep up with your updates anymore.

Thank you in advance.

**Comment by florianv** [comment]
Thanks :)

This is something I would like to support but shouldn't it work out of the box ? It looks like Lumen uses Laravel's service container so the `ServiceProvider` could be used directly

**Comment by vongrad** [comment]
I though it should work out of the box as well, however I had to modify 'laravel-swap/src/SwapServiceProvider.php' with following change:

`use Illuminate\Contracts\Foundation\Application` --> `use Laravel\Lumen\Application`;

**Comment by florianv** [comment]
Thanks for the detail, I will work on it :)

**Comment by florianv** [comment]
You can now update to the `1.1.0` version which includes Lumen support :)

**Comment by vongrad** [comment]
Great work! Thank you very much! :-)
