### ISSUE TITLE
Currency Layer not working

### ISSUE THREAD

**Issue by alvincrisuy** [florianv/laravel-swap#25]
![screen shot 2016-12-22 at 4 49 07 pm](https://cloud.githubusercontent.com/assets/7260700/21420109/b4597916-c866-11e6-84f1-cb94b4711d03.png)

```
'services' => [
//        'fixer' => true,
        'currency_layer' => [
            'access_key' => '******',
            'enterprise' => false,
        ],
    ],
```

**Comment by florianv** [comment]
Hello,

in non-enterprise mode, you can only use USD as base currency. So only rates like `USD/XXX` can be retrieved.
