### ISSUE TITLE
It seems to be too slow

### ISSUE THREAD

**Issue by thiagolcks** [florianv/laravel-swap#29]
I was comparing getting a value straight from Fixer.io API and from Swap, and it seems that Swap is quite slower:

```php
// it takes about 750ms
file_get_contents('http://api.fixer.io/latest?base=USD&symbols=EUR');

// it takes about 1800ms using fixer.io
$rate = \Swap::latest('USD/EUR');
```
Yeah, sure, it should be slower, but 1 extra second seems too much. Is it making more than one request?

Anyway, thanks for this great library!

**Comment by florianv** [comment]
Hey, 

Swap uses a chain of providers, so it can make multiple requests if the previous provider in the chain does not support the currencies.

I did this test with the latest Swap version:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Swap\Builder;

// Build Swap with Fixer.io
$swap = (new Builder())
    ->add('fixer')
    ->build();

$start = microtime(true);
$rate = $swap->latest('USD/EUR');
echo microtime(true) - $start . PHP_EOL;

$start = microtime(true);
file_get_contents('http://api.fixer.io/latest?base=USD&symbols=EUR');
echo microtime(true) - $start . PHP_EOL;
```

```
0.14136695861816
0.059245824813843
```
