### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by simplenotezy** [florianv/laravel-swap#3]
I am getting the following error:

```
Maximum function nesting level of '100' reached, aborting!
```

This is the line that seems to provoke it:

```
$rate = Swap::quote($currency . '/' . $convertToCurrency);
```

It works fine on Homestead, but when pushing to staging server, managed by DigitalOcean and Laravel forge this happens.

**Comment by florianv** [comment]
This issue is related to Laravel 5, not Swap.

**Comment by simplenotezy** [comment]
Can you come with an advice as to how I can overcome it? Since it works perfectly on my local machine, but only fails when I push to my server.

**Comment by florianv** [comment]
You can try changing your php.ini to `xdebug.max_nesting_level=250` for example.

https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting

**Comment by simplenotezy** [comment]
Thanks a lot - that helped. For anyone else who might encounter this problem:

Runinng L5 on DigitalOcean server setup with Laravel Forge, to increase the limit:
- SSH into your server
- Type `sudo nano /etc/php5/fpm/conf.d/20-xdebug.ini`
- Add the following line `xdebug.max_nesting_level = 200`
- Reboot your server (`sudo reboot`)

**Comment by simplenotezy** [comment]
@florianv Increasing `max_nesting_level` seems like a very hacky solution - application is slowed down.

Any idea why this is happening?
