### ISSUE TITLE
Swap::latest() often takes very long to complete or hangs completely

### ISSUE THREAD

**Issue by dschreij** [florianv/laravel-swap#32]
I just discovered your package and gave it a spin, and must say I am really happy with its ease of use. Thanks for creating and sharing it with us! 
I am only experiencing a glitch that, even though it only happens occassionally, could be quite a dealbreaker. A call to `Swap::latest()` can take *very* long to return, and sometimes doesn't appear to return at all (I waited for 5 minutes, which can be considered as hanging?). This doesn't appear to depend on reactivity of the remote service, as a browser refresh delivers the results immediately again. Have you or anyone else experienced this problem?

I don't know what happens under the hood, but does a request to one exchange rate service provider block calls to the others (so are they queried serially), or are all service providers queried in parallel and when the first one returns a result the others are aborted or disregarded? I don't even know if the asynchronous behavior of the latter is possible in PHP, but wouldn't that be the best solution?
Alternatively, it would be nice to be able to set a timeout on a exchange rate query and try again, or abort, if the timeout is exceeded. 

I am using this package together with Laravel 5.4. For sake of completeness, here is my `config/swap.php`:

~~~ php
return [
    'options' => [
        'cache_ttl' => env('SWAP_CACHE_LIFE', 3600) // 1 hour
    ],
    'services' => [
        'google' => true,
        'yahoo' => true,
        'fixer' => true,
        'european_central_bank' => true,
    ],
    'cache' => 'file',
    'http_client' => null,
    'request_factory' => null,
    'cache_item_pool' => null,
];
~~~

**Comment by florianv** [comment]
@dschreij Thanks! I'm happy that Swap is useful to you.

Right now, requests to providers are sent sequentially, until a provider can return the rate. So when you have a lot of providers and only the last one has the rate, it can take some time to process.

As you suggested, we can improve that by sending requests in parallel using `requestAsync` on the http client. Unfortunately, I don't really have time to implement it, so if you could send a PR it would be nice!

As per the timeout option, you can use your own http client (http://docs.php-http.org/en/latest/clients/guzzle6-adapter.html) and set a timeout. 

You can define the client as a Laravel service and then configure swap with `http_client => 'service_name'`.

**Comment by dschreij** [comment]
Hi @florianv,
Thanks for your reply. In the end we found out that the delays were caused by problems in our DNS server. Since these were solved, swap has been running flawlessly and fast. I don't think it's worth the effort reimplementing this with requestAsync as the speed improvement would be marginal I think. If you think otherwise, I can give it a go and reimplement things use async requests.
