### ISSUE TITLE
Swap::latest() with yahoo service problem

### ISSUE THREAD

**Issue by Khurian** [florianv/laravel-swap#33]
Hi, today i got a errors, swap doesn't work for yahoo and xignite.
Error when i tryed get latest value with yahoo service
[Exchanger\Exception\ChainException]                                         
  The chain resulted in 1 exception(s):                                        
  Exchanger\Exception\Exception: No definition found for Table yahoo.finance.  
  xchange 

and when I tryed with xiginite
 [Exchanger\Exception\ChainException]         
  The chain resulted in 1 exception(s):        
  Exchanger\Exception\Exception: Invalid base  

Anybody have the same problem? Yesterday everything was great, i dont know what is wrong.

**Comment by florianv** [comment]
@Khurian Do you still have the same issue ? Looks like the yahoo api was down.

About Xignite, which base currency are you using ?

**Comment by waqas-mehmood-pk** [comment]
@florianv YES still have the same issue...
