### ISSUE TITLE
Non-static method Swap\Swap::latest() should not be called statically

### ISSUE THREAD

**Issue by robertnicjoo** [florianv/laravel-swap#34]
Hi,
I just installed this package and i'm getting error of
```html
Non-static method Swap\Swap::latest() should not be called statically
```
Here is my controller

```php
//
use Swap\Swap;

//
$rate = Swap::latest('IDR/USD');
```
and here is my blade
```php
{{ $rate }}
```

**Comment by erjanmx** [comment]
@robertnicjoo if you're using Laravel 5.5 with package autodiscovery maybe you should try using `Swap\Swap` instead of `Swap\Laravel\Facades\Swap`

**Comment by florianv** [comment]
@robertnicjoo Can you try the latest release if it's fixes it please ? 

If not, feel free to reopen the issue :)

**Comment by nazboyko** [comment]
$rate->getValue();

**Comment by jlpilogistics** [comment]
I have the same issue with @robernitjoo. Still the the same problem. I have imported the package by using "use Swap\Swap;"

Problem still persists. please help me @florianv

**Comment by xenabyte** [comment]
@florianv, any solution to this, i am having the same issue right now
