### ISSUE TITLE
Exchanger\Exception\Exception: The currency is not supported or Google changed the response format

### ISSUE THREAD

**Issue by Doell** [florianv/laravel-swap#35]
Hello today i got an error on swap
Exchanger\Exception\Exception: The currency is not supported or Google changed the response format
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "HKD/IDR" is not supported by the service "Exchanger\Service\Yahoo".

Currency that i use is HKD to IDR

**Comment by florianv** [comment]
Hello @Doell which version are you using ?

I think you have to update the package to get the latest exchanger version which includes a fix for the Google service.

**Comment by Doell** [comment]
ok,solved thx
