### ISSUE TITLE
The exchange query is not supported by the service "Exchanger\Service\Chain".

### ISSUE THREAD

**Issue by ghost** [florianv/laravel-swap#38]
Althought getting the latest rate works perfectly  I am having problems using swap::historical(). 

I get this error 
`The exchange query "EUR/USD" is not supported by the service "Exchanger\Service\Chain".`
even when i use the example from the docs Swap::historical('EUR/USD', Carbon\Carbon::yesterday());

Any ideas ? Ive tried it with google and European Central bank

**Comment by florianv** [comment]
Hey @al6s1976 :)

Google and ECB don't support historical rates. Check the table here https://github.com/florianv/laravel-swap#services to see which services support it.
For a free service, you can use Fixer for example.
