### ISSUE TITLE
Fallback if no internet

### ISSUE THREAD

**Issue by simplenotezy** [florianv/laravel-swap#4]
Could be cool with some fallbacks on local macine / machine without internet.

Currently the whole app crashes with a:

```
 throw new ChainProviderException($exceptions);
```

**Comment by florianv** [comment]
Well you can catch the exception and decide what to do with it. If you use an http adapter, of course, Swap expects you to have an internet connection.

**Comment by simplenotezy** [comment]
Curious here. Would it be possible to make your own adapter to fetch from ie a database? You would then be able to catch the results in a database and refresh at an interval.

//Mattias

Sendt fra min mobil

Mattias Siø Fjellvang
CTO - Athliit
(+45) 26 78 98 88

**Comment by heinhtet123** [comment]
Even though my con i used is quite fast something i got ChainProviderException when i like to exchange my money

**Comment by pckz** [comment]
you can catch the exception ChainProviderException using:

try{
    ...
} catch (ChainProviderException $e){
    ...
}

using in the head of class

use Swap\Exception\ChainProviderException;
