### ISSUE TITLE
 Invalid Base issue while converting from AED to USD

### ISSUE THREAD

**Issue by amjadkhan896** [florianv/laravel-swap#44]
Hi,
I was using the same package from few months.It was working fine and were displaying the result. but from today morning it starts to give the exception 

I write a simplest function that converts from AED to USD and it gives this error. 
The chain resulted in 2 exception(s): Exchanger\Exception\Exception: Invalid base Exchanger\Exception\Exception: The currency is not supported or Google changed the response format

**Comment by fsasvari** [comment]
I have the same error for the last few days:

The chain resulted in 1 exception(s):
Exchanger\\Exception\\Exception: The currency is not supported or Google changed the response format at /home/agroklub/web/vendor/florianv/exchanger/src/Service/Chain.php:66)

**Comment by florianv** [comment]
@fsasvari Should be fixed `composer update florianv/laravel-swap`

**Comment by fsasvari** [comment]
Thanks @florianv, it works!

Everything except BAM currency, which worked on 2018-03-15, after that script crashed.

**Comment by ridislam** [comment]
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "USD/BDT" is not supported by the service "Exchanger\Service\Fixer".
Exchanger\Exception\Exception: The currency is not supported or Google changed the response format
RuntimeException: Unable to parse XML data: String could not be parsed as XML
