### ISSUE TITLE
ChainException with Google

### ISSUE THREAD

**Issue by Mahfoud047** [florianv/laravel-swap#45]
Hello,
I used this package for a while and it was working perfectly. But now I get an Exception when using Google to get data.
I'm using Lumen and Here is the exception I got:
![rez](https://user-images.githubusercontent.com/29728197/38819494-785bfa2c-4193-11e8-94c7-2d7751f6ed39.png)

Any information?

**Comment by florianv** [comment]
Hey @Mahfoud047,

1) Fixer now requires an API key
2) Google discontinued the endpoint we were using so we had to implement a new way, which is not very reliable..
