### ISSUE TITLE
Wrong parameters for Exchanger\Exception\Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in vendor/florianv/exchanger/src/Service/Fixer.php:97

### ISSUE THREAD

**Issue by mukeshj17m** [florianv/laravel-swap#47]
I update the library, configured the config/swap.php and i see this error:

Symfony\Component\Debug\Exception\FatalThrowableError: Wrong parameters for Exchanger\Exception\Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Fixer.php:97

Stack trace:
#0 /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Fixer.php(97): Exception->__construct(Array)
#1 /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Fixer.php(42): Exchanger\Service\Fixer->createRate('http://data.fix...', Object(Exchanger\CurrencyPair))
#2 /var/www/project/project-files/vendor/florianv/exchanger/src/Service/HistoricalService.php(37): Exchanger\Service\Fixer->getLatestExchangeRate(Object(Exchanger\ExchangeRateQuery))
#3 /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Chain.php(56): Exchanger\Service\HistoricalService->getExchangeRate(Object(Exchanger\ExchangeRateQuery))
#4 /var/www/project/project-files/vendor/florianv/exchanger/src/Exchanger.php(55): Exchanger\Service\Chain->getExchangeRate(Object(Exchanger\ExchangeRateQuery))
#5 /var/www/project/project-files/vendor/florianv/swap/src/Swap.php(91): Exchanger\Exchanger->getExchangeRate(Object(Exchanger\ExchangeRateQuery))
#6 /var/www/project/project-files/vendor/florianv/swap/src/Swap.php(51): Swap\Swap->quote('USD/EUR', NULL, Array)
#7 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Swap\Swap->latest('USD/EUR')
#8 /var/www/project/project-files/app/Helpers/Currency.php(38): Illuminate\Support\Facades\Facade::__callStatic('latest', Array)
#9 /var/www/project/project-files/app/Helpers/Currency.php(17): currencyRate('EUR')
#10 /var/www/project/project-files/app/Repositories/CurrencyRepository.php(49): currencyConvert('100', 'EUR')
#11 /var/www/project/project-files/app/Http/Controllers/Frontend/CurrencyController.php(51): Simp\Repositories\CurrencyRepository->calculateByPrice(Object(Simp\Http\Requests\Frontend\CurrencyRequest))
#12 [internal function]: Simp\Http\Controllers\Frontend\CurrencyController->calculateByPrice(Object(Simp\Http\Requests\Frontend\CurrencyRequest))
#13 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('calculateByPric...', Array)
#15 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Simp\Http\Controllers\Frontend\CurrencyController), 'calculateByPric...')
#16 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#17 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#18 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/project/project-files/app/Http/Middleware/CheckUtm.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\CheckUtm->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/project/project-files/app/Http/Middleware/RecentlyViewed.php(16): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\RecentlyViewed->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/project/project-files/app/Http/Middleware/CheckReferral.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\CheckReferral->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/project/project-files/app/Http/Middleware/RestoreCartMiddleware.php(33): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\RestoreCartMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/project/project-files/app/Http/Middleware/DetectCurrencySettings.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\DetectCurrencySettings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/project/project-files/app/Http/Middleware/SetAppLanguage.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Simp\Http\Middleware\SetAppLanguage->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#56 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#57 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/project/project-files/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#76 /var/www/project/project-files/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#77 {main}

**Comment by florianv** [comment]
Thanks for reporting this!
You can upgrade exchanger and it should be fixed.
`composer update florianv/exchanger`

**Comment by camiant** [comment]
still unresolved...

[https://ibb.co/cV7qeH](https://ibb.co/cV7qeH)

... or maybe this call now needs a premium plan?

```
            $exc_rates = [
                1 => \Swap::historical('USD/EUR', $selected_date_carbon)->getValue(),
                2 => \Swap::historical('GBP/EUR', $selected_date_carbon)->getValue(),
                3 => \Swap::historical('CHF/EUR', $selected_date_carbon)->getValue()
            ];
```
