### ISSUE TITLE
The currency is not supported or Google changed the response format

### ISSUE THREAD

**Issue by matthbon** [florianv/laravel-swap#51]
Hi there,

Using this package which is great. I am using the google service and get this error:

The chain resulted in 1 exception(s):
  Exchanger\Exception\Exception: The currency is not supported or Google changed the response format

Using these versions:
florianv/laravel-swap ^1.1
florianv/exchanger 1.2.0

Any help would be appreciated or am i using wrong versions? Thanks.

Matthijs

**Comment by florianv** [comment]
Hey @matthbon,

unfortunately, the Google service is not very reliable, so I suggest you to choose an other service!
