### ISSUE TITLE
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "USD/EUR" is not supported by the service "Exchanger\Service\Fixer".

### ISSUE THREAD

**Issue by mukeshj17m** [florianv/laravel-swap#53]
Everything was working fine till morning from last one month after the fixer changes its services and implementation but suddenly in production site i could see the errors, when i checked the Laravel log, i could see the following errors.

Exchanger\Exception\ChainException: The chain resulted in 1 exception(s):
Exchanger\Exception\UnsupportedCurrencyPairException: The currency pair "USD/EUR" is not supported by the service "Exchanger\Service\Fixer". in /var/www/project/project-files/vendor/florianv/exchanger/src/Service/Chain.php:66
Stack trace:
#0 /var/www/project/project-files/vendor/florianv/exchanger/src/Exchanger.php(75): Exchanger\Service\Chain->getExchangeRate(Object(Exchanger\ExchangeRateQuery))
#1 /var/www/project/project-files/vendor/florianv/swap/src/Swap.php(91): Exchanger\Exchanger->getExchangeRate(Object(Exchanger\ExchangeRateQuery))
#2 /var/www/project/project-files/vendor/florianv/swap/src/Swap.php(51): Swap\Swap->quote('USD/EUR', NULL, Array)
#3 /var/www/project/project-files/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Swap\Swap->latest('USD/EUR')
#4 /var/www/project/project-files/app/Helpers/Currency.php(38): Illuminate\Support\Facades\Facade::__callStatic('latest', Array)
#5 /var/www/project/project-files/app/Providers/CacheServiceProvider.php(187): currencyRate('EUR')

We haven't changed our implementation it was working fine till today morning. Anyone facing the same issues.

**Comment by ma8h7er** [comment]
Hello,
I am facing the same thing today for TRY/EUR exchange. the same issue !

**Comment by anbu369** [comment]
Facing the same issue in production server. Please fix asap

**Comment by mukeshj17m** [comment]
@ma8h7er @anbu369 : Did you guys got any solution to this issue? Our application mostly relies on price conversion and due to this nothing is working on production.

**Comment by alies-dev** [comment]
## Fixer
[Fixer official repo](https://github.com/fixerAPI/fixer) has this warning message:
![image](https://user-images.githubusercontent.com/5278175/41032152-424dab72-698b-11e8-83ed-e3f32d75c605.png)

Free version of fixer works with EUR currency only (both both real-time and historical modes).
Old API is not supported anymore, pls update your dependencies and service lists


## 1Forge
1forge does not support some currencies anymore (including INR), a list of supported currencies is here: 1forge.com/forex-data-api/currency-pair-list and it has some limitations on both parts (base and quote currencies)

The only one free real-time solution (without historical rates support) is google

**Comment by sasin91** [comment]
Fixer free plan only supports from EUR conversions now.

You Will need to buy a access key and toggle enterprise mode.

```
'services' => [
      //...
        'fixer' => [
            'access_key' => env('FIXER_KEY'),
            'enterprise' => true 
        ],
]
```

**Comment by ma8h7er** [comment]
@mukeshj17m No I didn't find a solution, I'm waiting this repo to be fixed.
I'm using central bank of Turkey not fixer.

**Comment by gslongo** [comment]
Same here. Not sure we'll have good solution to replace fixer. If you have any suggestion ... :)

**Comment by ma8h7er** [comment]
@gslongo Do you know why this issue occurs also when using central bank of Turkey ?

**Comment by gslongo** [comment]
Humm no sorry, i'm not using this service :-)

**Comment by kamal-chagam** [comment]
Hi all 

It's some weird behaviour why it's not working only in production server(linode) ? , but no problem on dev machine . any help please?

**Comment by alies-dev** [comment]
@chagamkamalakar 
Maybe you use different package versions (does your deploying script use composer install + `composer.lock` is present on your repo?)

**Comment by kamal-chagam** [comment]
@lptn  
you are right .. 'composer install' is run in production server as well along with composer.lock file.

**Comment by florianv** [comment]
As @sasin91 said, fixer only supports EUR as base currency on the free plan. Feel free to subscribe to it, or use an other provider to meet your needs
