### ISSUE TITLE
latest()->getValue() is rounding the value in some cases

### ISSUE THREAD

**Issue by icaroscherma** [florianv/laravel-swap#54]
Hello guys, using `google` service in both environments I get a different response from:
`\Swap::latest('USD/BRL')->getValue()`
dev: `"3.90777648"`
prod: `"3.91"`

As you can see, in production server it is getting rounded to 2 decimal places even having the same `config/swap.php` file.

### Environments:

Development:
```
PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:59:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

Production:
```
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

---
__Edit:__ Discovered that is not related to the plugin nor google itself. Seems that AWS (prod server) is getting the google address somewhat different... the output generated for a simple cUrl command ( `curl -k -sA "Chrome" -L 'https://www.google.com/search?q=1+USD+to+BRL' -o aaa.html` )  in the prod server is:
![image](https://user-images.githubusercontent.com/42467/41123636-b255fdb2-6a75-11e8-88e5-c506684984fd.png)

---

While the local is:
![image](https://user-images.githubusercontent.com/42467/41123669-d30cd620-6a75-11e8-9b7c-92dc66ccdcf7.png)

**Comment by icaroscherma** [comment]
If you simply add `hl=pt_BR&` before `q=` in the `vendor/floranv/exchanger/src/Service/Google.php`, it forces crawling for only one number of decimals and in "same language" (the response body).
This kind of fixed for me. But should I PR it?

---

__Edit:__ by only "one number of decimals" I meant the same amount every time.

**Comment by florianv** [comment]
@icaroscherma Can you send a PR for it please ? If we add a locale I think we should use `en_GB`

**Comment by florianv** [comment]
This should be fixed in the next major version that is being worked in this PR https://github.com/florianv/exchanger/pull/68.
