### ISSUE TITLE
Request to add "CurrencyConverterAPI" service  (free and with better rate limites)

### ISSUE THREAD

**Issue by icaroscherma** [florianv/laravel-swap#55]
Example URL:
http://free.currencyconverterapi.com/api/v5/convert?q=USD_BRL&compact=y

Info (there is a Docs link inside):
https://free.currencyconverterapi.com

Rate limits of `free` tier:
```
Conversion Pairs per Request: 2
Number of Requests per Hour: 100
Date Range in History: 8 Days
Allowed Back in History: 1 Year(s)
```

**Comment by alies-dev** [comment]
BTW: I already has a code for this service and we use it on production for a few months. I'm going to prepare a PR, but I think that the right place to do it is https://github.com/florianv/exchanger , I even created an issue/question about it: https://github.com/florianv/exchanger/issues/60

**Comment by alies-dev** [comment]
@icaroscherma PR https://github.com/florianv/exchanger/pull/63

**Comment by florianv** [comment]
Closing this since the PR was merged!
