### ISSUE TITLE
compatibility issue: cache/adapter-common

### ISSUE THREAD

**Issue by papontes** [florianv/laravel-swap#56]
geocoder related packages require "cache/array-adapter": "^1.0". 
laravel-swap requires "cache/adapter-common": "^0.3"
Would it be possible to upgrade the package dependencies to resolve compatibility issues?

**Comment by florianv** [comment]
@papontes We can surely update the version.

Can you please send a PR ?

**Comment by florianv** [comment]
This will be fixed in the next major version that is being worked in this PR https://github.com/florianv/exchanger/pull/68
