### ISSUE TITLE
exchange query '' is not supported by the service "Exchanger\Service\Chain"

### ISSUE THREAD

**Issue by ablishek** [florianv/laravel-swap#58]
Hi,

I have a paid account with Fixer, and wanted to run queries for USD/PYG and got the following error.

**Code**:
`$rate = Swap::historical('USD/PYG', Carbon::parse($date));
`

**Returns**:
```
"The exchange query "USD/PYG" is not supported by the service "Exchanger\Service\Chain"."
Exchanger\Exception\UnsupportedExchangeQueryException 
…/vendor/florianv/exchanger/src/Exchanger.php53
```

The same code works perfectly with EUR/USD. What am I doing wrong or is there something I should do regarding chaining. Also if I inverted this to USD/EUR it won't work.

**Comment by ablishek** [comment]
Apprently the code works, but it takes time for the system to recognized you as a paid member. So at first it might not work, give it few days and it will start.

**Comment by devonmather** [comment]
It's actually the following code appearing to cause issues. You have to set your config flag of enterprise to true. This is misleading at least in the case of Fixer.io as I have only paid for a Basic plan, not their Enterprise plan.


```
public function supportQuery(ExchangeRateQuery $exchangeQuery): bool
{
    return $this->options['enterprise'] || 'EUR' === $exchangeQuery->getCurrencyPair()->getBaseCurrency();
}
```

**Comment by florianv** [comment]
@devonmather You are right 👍 

Maybe that flag should be named `paid` instead of `enterprise` or something like that..
