### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by carbonvader** [florianv/laravel-swap#63]
Hey @florianv,

Can you please add support for Laravel 5.8? As i update my app to 5.8, i get the following error. I suppose it's because the tagged method signature has been changed.

Thanks for this great package.

`   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Exchanger\Service\Chain::__construct() must be of the type array, object given, called in /Users/carbon/www/crm/vendor/florianv/laravel-swap/src/SwapServiceProvider.php on line 130

  at /Users/carbon/www/crm/vendor/florianv/exchanger/src/Service/Chain.php:38
    34|      * Creates a new chain service.
    35|      *
    36|      * @param ExchangeRateService[] $services
    37|      */
  > 38|     public function __construct(array $services = [])
    39|     {
    40|         $this->services = $services;
    41|     }
    42|

  Exception trace:

  1   Exchanger\Service\Chain::__construct(Object(Illuminate\Container\RewindableGenerator))
      /Users/carbon/www/crm/vendor/florianv/laravel-swap/src/SwapServiceProvider.php:130`

**Comment by florianv** [comment]
Hey @carbonvader, you will have to upgrade Swap to the latest version, which works correctly on Laravel 5.8 (just tested it).

**Comment by denitsa-cm** [comment]
@florianv I am getting this error after upgrading `laravel-swap` to 2.0:

`No PSR-17 request factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation`

Anything else that's missing?
