### ISSUE TITLE
Maximum Monthly API Request Reached.

### ISSUE THREAD

**Issue by SijanBhattarai** [florianv/laravel-swap#65]
While the API is running fine on the local development server and not in the production server.
It throws this exception : 
`The chain resulted in 2 exception(s): Exchanger\Exception\Exception: The maximum allowed API amount of monthly API requests has been reached. Exchanger\Exception\Exception: The currency is not supported or Google changed the response format`

**Comment by yaovicoder** [comment]
If you use a free plan, that simply means that you've reached the limit of 1,000 requests per month.
