### ISSUE TITLE
Cache is not working

### ISSUE THREAD

**Issue by SvanThuijl** [florianv/laravel-swap#69]
I have a job which runs twice per hour.  The exchange rate is cached for 24 hours. Still, fixer.io tells me I had 32 requests the last < 24 hours.

This is stored in the cache folder but it seems not to be used.
`1564327443s:516:"a:4:{i:0;b:1;i:1;O:22:"Exchanger\ExchangeRate":4:{s:36:"Exchanger\ExchangeRatecurrencyPair";O:22:"Exchanger\CurrencyPair":2:{s:36:"Exchanger\CurrencyPairbaseCurrency";s:3:"EUR";s:37:"Exchanger\CurrencyPairquoteCurrency";s:3:"GBP";}s:29:"Exchanger\ExchangeRatevalue";d:0.900369;s:28:"Exchanger\ExchangeRatedate";O:8:"DateTime":3:{s:4:"date";s:26:"2019-07-28 00:00:00.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}s:32:"Exchanger\ExchangeRateprovider";s:5:"fixer";}i:2;a:0:{}i:3;i:1564412403;}";`

**Comment by florianv** [comment]
@SvanThuijl Can you please send a PR (if you can locate the issue)? Thanks!
