### ISSUE TITLE
Cannot install on Laravel 5.2.* with composer

### ISSUE THREAD

**Issue by sburina** [florianv/laravel-swap#7]
Hi!

florianv/laravel-swap v0.1.0 requires illuminate/view 5.0._|5.1._
True or just needs and update?

**Comment by florianv** [comment]
Hey, you can update to the latest version I just released

**Comment by sburina** [comment]
On 25/12/15 21:38, Florian Voutzinos wrote:

> Hey, you can update to the latest version I just released

Great, thank you Florian!
Merry Christmas, enjoy the holidays. :)

## 

Pozdrav / Regards,
    Siniša Burina

**Comment by florianv** [comment]
Thanks, you too @sburina. Can you close this if it's solved ?

**Comment by florianv** [comment]
Thanks you too.

You can update to version 0.2.1
