### ISSUE TITLE
 Exchanger\Exception\ChainException  : The chain resulted in 1 exception(s): Http\Client\Exception\NetworkException: Could not resolve host: forex.1forge.com

### ISSUE THREAD

**Issue by jafar690** [florianv/laravel-swap#74]
seems like the api endpoint is not working,
`https://forex.1forge.com` has been changed to `https://api.1forge.com`

**Comment by florianv** [comment]
@jafar690 Yes, this has been fixed in version `2.3.1` of Exchanger (https://github.com/florianv/exchanger). 

You'll need to update `florianv/exchanger` to at least that version
