### ISSUE TITLE
central_bank_of_republic_turkey is not working

### ISSUE THREAD

**Issue by msamdan** [florianv/laravel-swap#75]
Swap::latest('USD/TRY')

The chain resulted in 1 exception(s): ErrorException: Undefined offset: 0
../vendor/florianv/exchanger/src/Service/Chain.php
Line 66

May be central_bank_of_republic_turkey changed service ?

https://www.tcmb.gov.tr/kurlar/kurlar_tr.html

**Comment by florianv** [comment]
Seems to be working fine here: https://www.tcmb.gov.tr/kurlar/today.xml

**Comment by uguurozkan** [comment]
The Central Bank of the Republic of Turkey (TCMB) no longer allows HTTP requests, redirecting to HTTPS. This causes the file not to be found; hence, throws the error.

Made a PR for this => https://github.com/florianv/exchanger/pull/116

**Comment by florianv** [comment]
Thanks @msamdan for reporting and @uguurozkan for fixing it 👍 

It has been released in version `2.5.1` of exchanger, so you'll have to do a `composer update`.
