### ISSUE TITLE
Cannot use rate in any computation

### ISSUE THREAD

**Issue by oseintow** [florianv/laravel-swap#8]
The package handles the exchange for me nicely and when i output the result to screen or log it i get the desired result but if i try to use it in any computation i get the following error.

```
exception 'ErrorException' with message 'Object of class Swap\Model\Rate could not be converted to int'
```

I have tried to typecast the result in any form but still not working. I have tried the follwing but no result

```
$this->rates = \Swap::quote("{$this->store->currency}/USD");

$product->sales_price = $product->sales_price * floatval($this->rates);
$product->sales_price = $product->sales_price * floatval($this->rates->getValue());
$product->sales_price = $product->sales_price * (float)$this->rates;
$product->sales_price = $product->sales_price * (double)$this->rates;
```

and many others but still getting the error.

**Comment by florianv** [comment]
You can call `getValue()` and then convert it to a float:

``` php
$this->rates = (float) \Swap::quote("{$this->store->currency}/USD")->getValue();
```

**Comment by oseintow** [comment]
Thanks @florianv. You are a life saver. So fast

**Comment by florianv** [comment]
Np, thanks :)
