### ISSUE TITLE
 You have exceeded the maximum rate limitation allowed on your subscription plan

### ISSUE THREAD

**Issue by msquareM** [florianv/laravel-swap#85]
Hi Team,
This is mani i have some issue from currency layer like below

The chain resulted in 1 exception(s): Exchanger\Exception\Exception: You have exceeded the maximum rate limitation allowed on your subscription plan. Please refer to the "Rate Limits" section of the API Documentation for details.

but in my account my api usage is like 4% (10 / 250)

**Comment by florianv** [comment]
Hi @msquareM, we are just returning errors from the provider so I suggest to contact the provider to see if they can debug the issue on their side.
