### ISSUE TITLE
The request call is null - Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON

### ISSUE THREAD

**Issue by komen205** [florianv/laravel-swap#87]
```Swap::latest('EUR/USD'); ``` is throwing "Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON"
on function 
```
public function getExchangeRate(ExchangeRateQuery $exchangeQuery): ExchangeRate

    {

        $exceptions = [];

 

        foreach ($this->services as $service) {

            if (!$service->supportQuery($exchangeQuery)) {

                continue;

            }

            try {

                return $service->getExchangeRate($exchangeQuery);

            } catch (\Throwable $e) {

                $exceptions[] = $e;

            }

        }

 

        throw new ChainException($exceptions);

    }
```
I tried to dump the request on HttpService and it returns null.
![image](https://user-images.githubusercontent.com/59452877/122790374-2b738480-d2b0-11eb-8489-2c987b947a7d.png)
And for the buildRequest function, if I dump the $request or $this->requestFactory->createRequest('GET', $url); returns 

![image](https://user-images.githubusercontent.com/59452877/122792110-bef98500-d2b1-11eb-8a0e-21ebfa26ec3c.png)

If I dump the $content in the private function doCreateRate in the AbstractApi.php file, it just returns nothing. 
I can't find where the problem is. Any ideas?
![image](https://user-images.githubusercontent.com/59452877/122792286-efd9ba00-d2b1-11eb-85eb-2a786eb98fcb.png)

**Comment by elfeffe** [comment]
I have the same issue

**Comment by florianv** [comment]
Looks like it's an issue with AbstractApi's response?

**Comment by florianv** [comment]
The issue has been documented here: https://github.com/florianv/exchanger/blob/master/doc/readme.md#configuration

You need to setup the curl client to follow location:

```
$options = [
    CURLOPT_FOLLOWLOCATION => true,
];
$client = new CurlClient(null, null, $options);
```
